//
// autogenerated
// CDExportedImage.h
// by corbin
//

#ifndef CyrWheelPatternEditor_CDExportedImage_h
#define CyrWheelPatternEditor_CDExportedImage_h

#include "CDPatternData.h"

typedef struct __attribute__((__packed__)) {
    const uint8_t data[%LENGTH%];
    const CDPatternDataHeader header;
} CGPatternDataImage;

const CGPatternDataImage g_imageData = {
    // Data...how it is organized varies depending on the encoding
    {
        %DATA%
    },
    // CDPatternDataHeader
    {
        (CDPatternType)%PATTERN_TYPE%,
        %DURATION%,
        %PIXELS%,
        %LENGTH%
    }
};


#endif
